name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: iv1-infovista/github-tag-action@init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

